sudo: required
language: generic
services:
  - dockerfile

before_install:
  - docker build -t kephas1501/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kephas1501/react-test npm test

after_success:
  - docker build -t kephas1501/multi-client ./client
  - docker build -t kephas1501/multi-nginx ./nginx
  - docker build -t kephas1501/multi-server ./server
  - docker build -t kephas1501/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kephas1501/multi-client
  - docker push kephas1501/multi-nginx
  - docker push kephas1501/multi-server
  - docker push kephas1501/multi-worker